# Generated by Django 4.2.5 on 2023-09-11 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='latitute',
            new_name='latitude',
        ),
    ]
