version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/usr/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: "postgres"
    ports: 
      - "5432:5432"
