version: "3.8"

services:
  app:
    build: .
    env_file: .env
    volumes:
      - .:/usr/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: "blog"
      POSTGRES_PASSWORD: "postgres"
    ports: 
      - "5432:5432"
