# Generated by Django 3.0.4 on 2020-03-31 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('post', '0002_post_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_url',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
